tasks:
  tv:
    rss: https://iptorrents.com/t.rss?u=555980;tp=50a8a211519790951eac776f80fbd016;22;78;download
    series:
      - last week tonight
      - curb your enthusiasm
      - rick and morty
      - made for love
      - couples therapy
      - american crime story
      - succession
      - ten year old tom
      - loki
      - mandalorian
      - book of boba
      - south park
    quality: 480p+
    download: torrents
